### ISSUE TITLE
How to set up configuration ?

### ISSUE THREAD

**Issue by nasibulloh** [dezhik/sms-sender#2]
I need an example to configure SenderServiceConfiguration that loaded from enviorment "test.properties" file

**Comment by dezhik** [comment]
As it is said in doc: "There are necessary fields in configuration, which are used by authentication provider you picked. Authentication providers are implementations of AuthProvider, by default DefaultAuthProvider is used."
So in the most brief configuration test.properties could consist from one line:
`apiId=%your_personal_appId% // appId you got after sign up`

and create service config using properties file
```
SenderServiceConfigurationBuilder.create()
      .load(new FileInputStream("test.properties"))
      .build();
```

or without it
`SenderServiceConfigurationBuilder.create().setApiId(%your_personal_appId%).build();`

For testing purposes use 
`testSendingEnabled=true`
or
`setTestSendingEnabled(true)`
This would emulate successful sending without your balance being charged for actual SMS.

**Comment by nasibulloh** [comment]
Thank you very much I have done it

**Comment by dezhik** [comment]
Glad to help
