### ISSUE TITLE
I cannot send any more sms requestes

### ISSUE THREAD

**Issue by nasibulloh** [dezhik/sms-sender#3]
Hi. I have been used sms.ru in Java language. I tried to send sms with 
SMSRuSendRequest and SMSRuCostRequest but I sent sms via only SMSRuCostRequest but I could not send any more from this Class.I got smscode with any timeout. Please help me to solve these problems I need more examples.

**Comment by dezhik** [comment]
> I tried to send sms with SMSRuSendRequest and SMSRuCostRequest but I sent sms via only SMSRuCostRequest but I could not send any more from this Class

You can't send sms with SMSRuCostRequest. SMSRuCostRequest does nothing except checking if sending is available, returning total price / number of SMS needed (>1 in case if message is too long).
You can always check which code api return by following the page of specific api method, e.g. cost method is described here http://sms.ru/api/cost

Here is api response status mapping into Java object [SMSRuResponseStatus](https://github.com/dezhik/sms-sender/blob/master/src/main/java/ru/dezhik/sms/sender/api/smsru/SMSRuResponseStatus.java)

> I got smscode with any timeout.
Be specific, which SMSRuResponseStatus or code are you receiving?

You can always set returnPlainResponse flag on your config - this could dramatically help you debugging an app.
SenderServiceConfigurationBuilder.create().setTestSendingEnabled(true)
or by adding returnPlainResponse=true into your config file if you are using one.

**Comment by nasibulloh** [comment]
Ok I will try to implement. But I want to say that If you write more documentation with examples It will be   better. For example I could not find any example to send sms and others.

**Comment by dezhik** [comment]
Added couple new examples
https://github.com/dezhik/sms-sender#usage-examples

> For example I could not find any example to send sms and others.

There is a list of implemented API methods 
https://github.com/dezhik/sms-sender#smsru-api-requests

The best way is always to look at the code. Open request class you are interested in and pay attention to its fields. 
Handler's `validate()` method will check all necessary params for such type of request. 
If it is not obvious for you which API method corresponds to the Request class - than in the `getMethodPath()` method you can find API path and take a look at the official documentation for possible response codes and etc.
